# Read the documentation at https://github.com/thephpleague/flysystem-bundle/blob/master/docs/1-getting-started.md
flysystem:
    storages:
        avatars.storage:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/public/%avatar_uploads%'
        categories.storage:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/public/%category_uploads%'
        products.storage:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/public/%product_uploads%'
        banners.storage:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/public/%banner_uploads%'